// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LEFT_PAREN-0]
	_ = x[RIGHT_PAREN-1]
	_ = x[LEFT_BRACE-2]
	_ = x[RIGHT_BRACE-3]
	_ = x[COMMA-4]
	_ = x[DOT-5]
	_ = x[MINUS-6]
	_ = x[PLUS-7]
	_ = x[STAR-8]
	_ = x[SEMICOLON-9]
	_ = x[EQUAL-10]
	_ = x[EQUAL_EQUAL-11]
	_ = x[BANG-12]
	_ = x[BANG_EQUAL-13]
	_ = x[LESS-14]
	_ = x[LESS_EQUAL-15]
	_ = x[GREATER-16]
	_ = x[GREATER_EQUAL-17]
	_ = x[EOF-18]
}

const _TokenType_name = "LEFT_PARENRIGHT_PARENLEFT_BRACERIGHT_BRACECOMMADOTMINUSPLUSSTARSEMICOLONEQUALEQUAL_EQUALBANGBANG_EQUALLESSLESS_EQUALGREATERGREATER_EQUALEOF"

var _TokenType_index = [...]uint8{0, 10, 21, 31, 42, 47, 50, 55, 59, 63, 72, 77, 88, 92, 102, 106, 116, 123, 136, 139}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
