// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LEFT_PAREN-0]
	_ = x[RIGHT_PAREN-1]
	_ = x[LEFT_BRACE-2]
	_ = x[RIGHT_BRACE-3]
	_ = x[COMMA-4]
	_ = x[DOT-5]
	_ = x[MINUS-6]
	_ = x[PLUS-7]
	_ = x[STAR-8]
	_ = x[SEMICOLON-9]
	_ = x[EQUAL-10]
	_ = x[EQUAL_EQUAL-11]
	_ = x[BANG-12]
	_ = x[BANG_EQUAL-13]
	_ = x[LESS-14]
	_ = x[LESS_EQUAL-15]
	_ = x[GREATER-16]
	_ = x[GREATER_EQUAL-17]
	_ = x[SLASH-18]
	_ = x[STRING-19]
	_ = x[EOF-20]
	_ = x[NUMBER-21]
	_ = x[IDENTIFIER-22]
	_ = x[AND-23]
	_ = x[CLASS-24]
	_ = x[ELSE-25]
	_ = x[FALSE-26]
	_ = x[FOR-27]
	_ = x[FUN-28]
	_ = x[IF-29]
	_ = x[NIL-30]
	_ = x[OR-31]
	_ = x[PRINT-32]
	_ = x[RETURN-33]
	_ = x[SUPER-34]
	_ = x[THIS-35]
	_ = x[TRUE-36]
	_ = x[VAR-37]
	_ = x[WHILE-38]
}

const _TokenType_name = "LEFT_PARENRIGHT_PARENLEFT_BRACERIGHT_BRACECOMMADOTMINUSPLUSSTARSEMICOLONEQUALEQUAL_EQUALBANGBANG_EQUALLESSLESS_EQUALGREATERGREATER_EQUALSLASHSTRINGEOFNUMBERIDENTIFIERANDCLASSELSEFALSEFORFUNIFNILORPRINTRETURNSUPERTHISTRUEVARWHILE"

var _TokenType_index = [...]uint8{0, 10, 21, 31, 42, 47, 50, 55, 59, 63, 72, 77, 88, 92, 102, 106, 116, 123, 136, 141, 147, 150, 156, 166, 169, 174, 178, 183, 186, 189, 191, 194, 196, 201, 207, 212, 216, 220, 223, 228}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
